name: Deploy Spring Boot

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Setup Java
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '21'

    - name: Build JAR
      run: mvn clean package -DskipTests

    - name: Copy JAR to VPS
      uses: appleboy/scp-action@master
      with:
        host: 163.245.215.37
        username: root
        key: ${{ secrets.SSH_KEY }}
        source: "target/*.jar"
        target: "/root/med/"

    - name: Restart Application
      uses: appleboy/ssh-action@master
      with:
        host: 163.245.215.37
        username: root
        key: ${{ secrets.SSH_KEY }}
        script: |
          cd /root/med
          PID=$(pgrep -f medtrackfit || true)
          if [ ! -z "$PID" ]; then
            kill -9 $PID
          fi
          nohup java -jar medtrackfit-0.0.1-SNAPSHOT.jar > app.log 2>&1 &